name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  version-check:
    uses: ./.github/workflows/Version.yml

  run-build-upload:
    needs: version-check
    uses: ./.github/workflows/Wheels.yml
    secrets:
      TESTPYPI_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}

  trigger-windows1:
    needs: run-build-upload
    uses: ./.github/workflows/WindowsExe.yml

  trigger-windows2:
    needs: run-build-upload
    uses: ./.github/workflows/WindowsInstaller.yml

  trigger-mac:
    needs: run-build-upload
    uses: ./.github/workflows/MacOS.yml

  upload-release:
    needs:
      - trigger-windows1
      - trigger-windows2
      - trigger-mac
    uses: ./.github/workflows/UploadRelease.yml

  upload-pypi:
    needs:
      - trigger-windows1
      - trigger-windows2
      - trigger-mac
    uses: ./.github/workflows/PyPI.yml



